library(raster)
library(ncdf4)
library(R.matlab)
library(ggplot2)
# library(ggbreak)

f=nc_open('../marginal_land/ml_kaiyu_fraction.nc')
ml = ncvar_get(f,"layer")
nc_close(f)
#because this was generated by the writeRaster, we need to flip it upside down
ml1 = t(apply(ml,1,rev))

# source('write2NC.R')
# writeToNC('test.nc',1:138,1:195,1,'test','','float',list(ml1))
f=nc_open('../yield_maps//conus_masks/conus_mask_heartland_withFL.nc')
east_US = ncvar_get(f,"conus")  #1: eastern part of US
nc_close(f)

ml_east = ml1
ml_east[east_US!=1] = NaN

#these max yield results are used to calculated NPP
yield_multiyear_hist_all = readRDS('../yield_maps/yield_results/all_years_2000_2014.rds')
yield_multiyear_futu_all = readRDS('../yield_maps/yield_results/all_years_2036_2050.rds')
yield_max_multiyear_hist = yield_multiyear_hist_all[[2]]
yield_max_multiyear_futu = yield_multiyear_futu_all[[2]]
yield_multiyear_hist     = yield_multiyear_hist_all[[1]]
yield_multiyear_futu     = yield_multiyear_futu_all[[1]]

yield_hist_ncfile = 
  '../yield_maps/yield_results/multi_crop_yield_mpi_2000_2014_r7.nc'
yield_futu_ncfile = 
  '../yield_maps/yield_results/multi_crop_yield_mpi_2036_2050_r7.nc'
f=nc_open(yield_hist_ncfile)
yield_hist = ncvar_get(f,"yield")
yield_hist_sd = ncvar_get(f,"yield_std")
nc_close(f)
f=nc_open(yield_futu_ncfile)
yield_futu = ncvar_get(f,"yield")
yield_futu_sd = ncvar_get(f,"yield_std")
nc_close(f)

crop_allocation_hist = 
  '../yield_maps/crop_allocation_index/max_index_yield_based_hist_r7_new.mat'
crop_allocation_futu = 
  '../yield_maps/crop_allocation_index/max_index_yield_based_futu_r7_new.mat'
location_hist = readMat(crop_allocation_hist)
location_hist = location_hist$max.index1
location_futu = readMat(crop_allocation_futu)
location_futu = location_futu$max.index1

#calculate total biomass on ML
ml_hectare = ml_east * 900 * 100 #km2 to hectare

# source('write2NC.R')
# writeToNC('ml_kaiyu_hectare.nc',1:138,1:195,1,'ml','','float',list(ml_hectare))

for (i in 1:3){
  print(sum(ml_hectare[location_hist==i],na.rm=TRUE))
  print(sum(ml_hectare[location_futu==i],na.rm=TRUE))
}

years = 2000:2014
output_hist = data.frame(yield=NA,scenario='Recent',crop_type=c('Miscanthus','Switchgrass','Energycane'))
total_biomass_hist     = array(NaN,c(length(years),3))
total_biomass_max_hist = array(NaN,c(length(years),3))
for (i in 1:3){
  crop_yield_i = yield_hist[,,i]
  crop_yield_sd_i = yield_hist_sd[,,i]
  print('historical mean yield:')
  print(mean(crop_yield_i[location_hist==i],na.rm=TRUE))
  print(mean(crop_yield_sd_i[location_hist==i],na.rm=TRUE))
  yield_all = crop_yield_i * ml_hectare
  output_hist$yield[i] = sum(yield_all[location_hist==i],na.rm=TRUE)
  
  #calc multiple years' biomass
  for (j in 1:length(years)){
    crop_yield_i = yield_multiyear_hist[,,j,i]
    yield_all = crop_yield_i * ml_hectare
    total_biomass_hist[j,i] = sum(yield_all[location_hist==i],na.rm=TRUE)
    crop_yield_max_i = yield_max_multiyear_hist[,,j,i]
    total_biomass_max_hist[j,i] = mean(crop_yield_max_i[location_hist==i],na.rm=TRUE)
  }
}

years = 2036:2050
output_futu = data.frame(yield=NA,scenario='Future',crop_type=c('Miscanthus','Switchgrass','Energycane'))
total_biomass_futu = array(NaN,c(length(years),3))
total_biomass_max_futu =array(NaN,c(length(years),3))
for (i in 1:3){
  crop_yield_i = yield_futu[,,i]
  crop_yield_sd_i = yield_futu_sd[,,i]
  print('future mean yield:')
  print(mean(crop_yield_i[location_futu==i],na.rm=TRUE))
  print(mean(crop_yield_sd_i[location_futu==i],na.rm=TRUE))
  yield_all = crop_yield_i * ml_hectare
  output_futu$yield[i] = sum(yield_all[location_futu==i],na.rm=TRUE)
  
  #calc multiple years' biomass
  for (j in 1:length(years)){
    crop_yield_i = yield_multiyear_futu[,,j,i]
    yield_all = crop_yield_i * ml_hectare
    total_biomass_futu[j,i] = sum(yield_all[location_futu==i],na.rm=TRUE)
    crop_yield_max_i = yield_max_multiyear_futu[,,j,i]
    total_biomass_max_futu[j,i] = mean(crop_yield_max_i[location_futu==i],na.rm=TRUE)
  }
}

total_biomass_max_hist = total_biomass_max_hist * 0.5 * 100 #Mg/ha to g C /m2
total_biomass_max_futu = total_biomass_max_futu * 0.5 * 100 #Mg/ha to g C /m2
NPP_hist = colMeans(total_biomass_max_hist)
NPP_futu = colMeans(total_biomass_max_futu)
NPP_hist_sd = apply(total_biomass_max_hist,2,sd)
NPP_futu_sd = apply(total_biomass_max_futu,2,sd)

error_bar_hist = apply(total_biomass_hist/1e9,2,sd)
error_bar_futu = apply(total_biomass_futu/1e9,2,sd)

output_all = rbind(output_hist,output_futu)
output_all$yield = output_all$yield /1e9 #ton to billion ton

output_all$sd = c(error_bar_hist,error_bar_futu)

bars_order = c(1:6)
ggplot(data = output_all,aes(x=reorder(scenario,bars_order), y=yield,
                             fill=reorder(crop_type,bars_order)))+
  geom_bar(stat='identity',position=position_dodge())+
  geom_errorbar(aes(ymin=yield-sd, ymax=yield+sd), width=.2,
                position=position_dodge(.9)) +
  labs(x="", y = "Biomass (billion tonnes)")+
  scale_fill_manual(values=c('blue3','green3','pink'),name = '')+
  # scale_y_break(breaks=c(0.001,0.1),scales=3)+   #this can break the y axis if needed!
  theme_bw(base_size = 16)

#gap barplot
# from <- 0.001
# to   <- 0.003
# gap.barplot(output_all$yield, gap=c(from,to), col=c(1:6),
#             xlab="index", ylab="value")
# axis.break(2, from, breakcol="snow", style="gap")
# axis.break(2, from*(1+0.02), breakcol="black", style="slash")
# axis.break(4, from*(1+0.02), breakcol="black", style="slash")
# axis(2, at=from)
